app/components/ngao/arclight/group_component.html.erb, app/components/ngao/arclight/group_component.rb, app/controllers/catalog_controller.rb
This commit will add the collection id (`unitid`) to the search results.
when viewing in the `Grouped by collection` view.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/23
=> 🎁 Add collection id to search results

app/assets/stylesheets/breadcrumbs.scss, app/components/ngao/arclight/breadcrumbs_hierarchy_component.html.erb
This commit will revert the styling for the breadcrumbs to default ArcLight for now.  We will assess if this needs to change or not at a later point.  Also added an obvious comment to what we overrode in the breadcrumbs_hierarchy_component partial.
=> 💄 Revert breadcrumbs styling to default ArcLight

app/controllers/application_controller.rb, config/routes.rb
This commit will block the search_history routes from being accessed by users that are crafty enough to navigate to them directly.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/22
=> 🎁 Remove search history route

app/assets/stylesheets/arclight.scss, app/assets/stylesheets/brand.css, app/assets/stylesheets/iu_variables.scss, app/assets/stylesheets/ngao-footer.scss, app/components/blacklight/search_navbar_component.html.erb, app/controllers/pages_controller.rb, app/views/pages/about.html.erb, app/views/pages/contribute.html.erb, app/views/pages/help.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_iu_footer.html.erb, app/views/shared/_ngao_footer.html.erb, app/views/shared/_static_pages_links.html.erb, app/views/shared/_user_auth_links.html.erb, config/locales/arclight.en.yml, config/routes.rb
IU has a custom homepage with static content links. The archives_online application should have the same.
Refs:
There was no footer and no links to About page or Contribute page. There was no `Get search help` link or corresponding Help page.
The footer exists with custom branding that matches the current production site. There are link for the About and Contribute pages that take the use to the appropriate static pages. There is a `Get search help` link in the search area and a corresponding Help page.
https://github.com/user-attachments/assets/b3ba7318-2693-45c2-b9db-85228a1a3f06
- The user can click the `Get search help` link and be taken to the Help page.
- The footer exists on the home page with custom branding. 
- The user can click the `About` link and be taken to the About page.
- …
=> I20 custom homepage

app/controllers/catalog_controller.rb, data/softserv_VAD9218.xml, lib/arclight/traject/ead2_config.rb
This commit brings over a lot from NGAO but I hesitate to copy it directly since a lot of the changes are either not relevant or are already the way Arclight does things.  I did the logic for the `context.clipboard[:repository]` in the `ead2_config` file to look for the campus if the REPOSITORY_ID wasn't provided which might be useful in this time of transition.  This could be reverted back after we hand this project back to IU.
A lot of the issues that came from the reviewing of the EAD implementation should be fixed in this commit.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/45
- https://github.com/scientist-softserv/archives_online/issues/46
- https://github.com/scientist-softserv/archives_online/issues/47
- …
=> ⚙️ Configure `ead2_config` and `CatalogController`

config/locales/arclight.en.yml
This removes any translation that calls variables and reverts to Arclight.  We are seeing some the literal %{...} come through in the view.
=> ⚙️ Remove some custom locale translations

app/controllers/catalog_controller.rb
This commit will adjust the solr field to what they are indexed to in this application's ead2_config.  Originally, the fields were brought in from NGAO and it didn't match up exactly.  Ex. `repository_sim` vs `repository_ssim`.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/19
=> 🐛 Fix solr fields for facets

.rubocop.yml, Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, app/assets/stylesheets/arclight.scss, app/controllers/catalog_controller.rb, app/models/search_builder.rb, config/environments/development.rb, config/routes.rb
e64ec528d42cc0e4bc448717252fc5ad7f9f94fe
This commit adds the Blacklight Range Limit gem and minor changes to
make it work.  The assets are currently not working yet though.
f02ec7470ee4c4f493d332990056bac2f7972438
It seems that Blacklight Range Limit and Rails 7/Blacklight 8 don't work
well together.  The javascript does not seem to be working properly.
I've hidden the UI for the parts that don't work for now borrowing from
Standford's Arclight solution.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/53
- https://github.com/projectblacklight/blacklight_range_limit/issues/236
- https://github.com/sul-dlss/stanford-arclight/pull/529
Year facet was not present.
Year facet is now present but features like the chart and the slider are not working with Rails 7/Blacklight …
=> I53 blacklight range limit

app/assets/stylesheets/overrides_with_rivet_styles.scss, app/helpers/arclight_helper_decorator.rb
fe090a47378fd714fa4b1f92ab46dff1a7b9ac30
This commit will style the collection show page with Rivet styles.
faf4d4e951e0a5f837361dbd20023c179e0d8095
The `View all of our collections` link was not working correctly because
it was using default Arclight params.  This commit will add the correct
params to the link.
Ref:
- #26 
Styles on the collection show page was stock Arclight/Blaclight.  The `View all of our collections` link did not go to the correct faceted search.
Rivet styles are applied to the collection show page.  The `View all of our collections` link now goes to the correct faceted search.
=> 💄 I26 styling collection show page

app/assets/images/rivet_icons/arrow-anchor-down-right.svg, app/assets/images/rivet_icons/info-circle-solid.svg, app/assets/stylesheets/overrides_with_rivet_styles.scss, data/softserv_InU-Li-VAE1866.xml, lib/arclight/traject/ead2_config.rb, lib/ngao/year_range.rb
be950975e41f9ffddcea653f087e303389ac0194
This commit adding Rivet styling to the actions box container on the
collection show page.  All that was really done was converting the
dropdown buttons to the Rivet buttons and align some elements better.
ebb96d5b1eed372d89ec66221e59bfa7563c8786
This commit adds minor styles on the Collection overview section.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/26
49fafe15d7391e6b56f61f6e98e83ca51da39b99
This commit adds basic styling to the Start Over and Back to Search
butttons.
5e00e48d43a4be4473dc40acd05ce361c7f0f7ec
This commit styles the breadcrumbs to be in line with the rivet styles.
89744afa87a4dac2ad838fff81347d345249b24d
This commit will style the request button on the catalog show page to
match the Rivet primary button. …
=> I26 styling collection show

config/routes.rb
This commit will override Arclight's route for `/collections` to change `level` to `leve_ssim`.
Clicking the `Collections` link on the navbar would take you to a blank search.
Clicking on the `Collections` link now takes you to a faceted search.
=> ⚙️ Override `/collections`

.rubocop.yml, app/assets/stylesheets/overrides_with_rivet_styles.scss, app/components/blacklight_range_limit/range_form_component.html.erb, app/components/blacklight_range_limit/range_form_component.rb
b5c4aa24194f5e6aa793c0f160620710238a6627
This commit will override the Blacklight Range Limit v8.5.0 to swap the
submit button in the div.visually-hidden with the submit buton that is
not in the div.visually-hidden.  Also adding tabindex="-1" to the hidden
one. This will pass the Siteimprove Accessibility Checker.
The entire RangeFormComponent class had to be brought over because in
view components, we can't just bring over the view we want to override.
I am adding the class to the rubocop ignore because I don't want to
alter the contents since it's only here to support its view file to be
loaded.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/68
a2e4eed93aeeae26d5d6f655a983d5b525e2a9db
Prior to this commit, when tabbing through the facets, there was no
visual …
=> I68 hidden element has focusable content

app/views/shared/_main_menu_links.html.erb, config/routes.rb
This commit will revert a previous override of the Arclight route that changes the default params from `level` to `level_ssim`.  That solved the issue for the `Collections` link pointing to the correct faceted search, it broke all other facet searches.  If I changed the route directly in Arclight to add the `level_ssim` param, it worked fine.  If I brought it in locally then the other facets break.  I'm not sure why it was doing that but with regards to time, I going to override the link of the `Collections` to the correct faceted search.
=> ⚙️ Revert the Arclight route override

app/assets/stylesheets/overrides_with_rivet_styles.scss
This commit will add a 1.5rem (24px) height to all breadcrumb links for better accessibility and usability.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/66
=> ♿️ Increase clickable area of breadcrumbs

app/assets/stylesheets/overrides_with_rivet_styles.scss
This commit will add an underline for all text links in the app.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/70
=> 💄 All text links must be underlined

app/components/ngao/arclight/search_result_breadcrumbs_component.html.erb, app/components/ngao/arclight/search_result_breadcrumbs_component.rb, app/controllers/catalog_controller.rb
This commit will guard against rendering an empty breadcrumb element when there are no breadcrumbs to display.  The check we are doing is to see if the html string has the `breadcrumb-item` class.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/67
Before:
After:
=> ♿️ Don't render an empty breadcrumb element

app/views/shared/_main_menu_links.html.erb
In the previous commit where we override main_menu_links, I forgot to add group=true onto it.
=> 🐛 Add group=true to collections link

app/assets/stylesheets/overrides_with_rivet_styles.scss
This commit will increase the size of the breadcrumb links and repository links to make them at least 24x24 pixels.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/79
=> ♿️ Increase interactive element size

app/assets/stylesheets/overrides_with_rivet_styles.scss
This commit will remove the hidden overflow on the search contraints on the catalog search page when doing a faceted search.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/80
Before:
After:
=> ♿️ Stop search text from clipping

app/assets/stylesheets/arclight.scss, app/assets/stylesheets/uv.scss
67d5301ec2e9809d9210791363efa7178bb4e766
This comit will make the UV viewer responsive to the viewport width.
This will prevent the UV from being too far off to the right of the
screen and forcing a horizontal scroll bar.
Ref:
- https://github.com/scientist-softserv/archives_online/issues/81
f039b48cde32cdcd04cb1dde5a63d3e1b48f4d36
The arclight.scss automatically imports the other scss files so we don't
need an extra import.  In fact, this was double importing the styles
making the styles appear twice in the compiled css.
https://github.com/user-attachments/assets/4d149588-1be4-43cd-ade5-7ff2c1f466d0
=> I81 responsive uv

.rubocop.yml, Gemfile, Gemfile.lock, app/components/blacklight/start_over_button_component_decorator.rb
69396595e3211b1801c873aba197638b4c0322b2
In production, clicking the "Start Over" button takes the user back to the homepage. Currently, it performs an empty search instead.
This PR overrides the default behavior to restore parity with production.
Issue: https://github.com/notch8/archives_online/issues/97
43c011b87311cd5ef5d21cc6020647ff70cfdb00
Devs were unable to run rubocop.
=> I97 update start over button link

app/controllers/catalog_controller.rb
The Names and Subject links in search results weren't properly filtering. I updated their configuration in the catalog controller, which aligns with Arclight's default behavior and matches production.
Issue:
- #91
=> [i91] - :bug: Fix Name and Subject facet search behavior

app/controllers/catalog_controller.rb
The "View all" link in grouped search results wasn't properly filtering by collection because the facet field configuration in catalog_controller.rb didn't match [Arclight's](https://github.com/projectblacklight/arclight/blob/main/lib/generators/arclight/templates/catalog_controller.rb#L141) expected format. Updated the collection facet configuration to use the 'collection' key while maintaining the 'collection_ssim' Solr field, which aligns with Arclight's default behavior and matches production.
Issue:
- https://github.com/notch8/archives_online/issues/93
=> [i93] - Fix collection facet behavior in "View all" results

app/controllers/catalog_controller.rb
This swaps the display of scope content and biographical/historical notes for parity with production.
Issue:
- #104
https://archives.iu.edu/catalog/ua044
=> [i104] - swap order of scopecontent and bioghist

README.md, app/components/ngao/arclight/collection_context_component.html.erb, app/components/ngao/arclight/collection_context_component.rb, app/components/ngao/arclight/collection_info_component.html.erb, app/components/ngao/arclight/collection_info_component.rb, app/components/ngao/arclight/sidebar_component.rb, app/controllers/catalog_controller.rb, config/locales/arclight.en.yml
Ref:
- https://github.com/notch8/archives_online/issues/101
The Collection ID number was in the `More Info` dropdown menu. 
The Collection ID number is in the top right corner of the Collection section.
<details>
</details>
<details>
</details>
Added notes to the README on the process for overriding Arclight views.
=> 🎁 Exposing Collection ID Number

app/assets/stylesheets/arclight.scss
Breadcrumbs overlapped when a link's text was too long
Issue:
- #88
=> [i88]- Allow search result breadcrumb items to expand vertically

app/controllers/catalog_controller.rb
Removes the 'abstract_or_scope' index field from catalog controller to fix duplication issue: A user would see the same data twice when performing a catalog search.
Issue:
- #108
=> [i108] - removes dupe scope content in catalog search results

app/components/ngao/arclight/document_component.html.erb, app/models/solr_document.rb, lib/arclight/traject/ead2_component_config.rb, lib/arclight/traject/ead2_config.rb
This commit will add HTML rendering for titles on the components so that if the EAD says something like <title render=\"italic\">The Hill</title> then it will be converted to <em>The Hill</em> on the show page.
Ref:
- https://github.com/notch8/archives_online/issues/102
=> 🎁 Add html render support for unit titles

lib/arclight/traject/ead2_config.rb
Ref:
- https://github.com/notch8/archives_online/pull/new/i107-extents-display
Modifying `extent_ssm` and `extent_tesim` to format the XML tags nested within physical description to differentiate between the space occupied and the description of the physical containers.
Previously: `15 cubic feet Seven boxes, 24 x 15 x 10 1/4"; 26 folder boxes, 11.5 x 6.5 x 5.5"; bulk of documents`
With this commit: `15 cubic feet (Seven boxes, 24 x 15 x 10 1/4"; 26 folder boxes, 11.5 x 6.5 x 5.5"; bulk of documents)`
<details>
</details>
<details>
</details>
=> 🎁 Formatting applied to all Extents display

app/controllers/catalog_controller.rb
Issue:
- #133
related:
- #91
Clicking on a linkted term (creator) should perform a faceted search.
clicking on creator performed an empty search =>
=> 🎁 [i133] - linked Creator performs facet search

.gitignore, Dockerfile, app/assets/stylesheets/print.scss, app/components/ngao/arclight/document_download_component.rb, app/components/ngao/arclight/sidebar_component.rb, app/models/ead_processor.rb, app/templates/template.xslt, bin/web, chart/templates/deployment.yaml, config/downloads.yml, lib/tasks/index.rake
f10276b4c082d485fccfdce057afe4d52e890203
This commit will bring in some changes to make the printable view show
up.  It is a WIP because currently we have nothing to download.
Ref:
- https://github.com/notch8/archives_online/issues/111
9a39e4c877841a9810e30c88e1577504688a8c96
This commit will copy over print.scss, ead_processor.rb, and the
template.xslt as is with no changes straight from main.
1deec85ca1672ddd72544b2748ed0655ec064c62
This commit will alter the original print.scss and ead_processor.rb from
Archives Online main.  The screen styles weren't getting applied so I'm
moving it into the base ead-print style.  Also, adding some logic in the
EadProcessor to ensure that we are getting the same html file name as
the id of the document.
31d269197d95f5eed57779940c899e9f122a2dcf
This …
=> I111 enable printable view functionality

app/components/ngao/arclight/document_collection_hierarchy_component.html.erb, app/components/ngao/arclight/document_collection_hierarchy_component.rb, app/views/catalog/hierarchy.html.erb
This commit will prepend the "Series" and "Subseries" level to the title for the hierarchy list.
Ref:
- https://github.com/notch8/archives_online/issues/106
=> 🎁 Prepend "Series" and "Subseries" to title

app/components/ngao/arclight/collection_info_component.html.erb, config/locales/arclight.en.yml
Ref:
- https://github.com/notch8/archives_online/issues/105
The More Info dropdown had the terms `Collections` and `Items`
The More Info dropdown uses only the term `Items`
<details>
</details>
<details>
</details>
=> 🎁 Standardizes Terminology in More Info Dropdown

.gitignore, app/models/ead_processor.rb, chart/templates/deployment.yaml, lib/tasks/index.rake
This commit will now make it possible to generate downloadable EAD files every time we index using the rake task.
Ref:
- https://github.com/notch8/archives_online/issues/112
=> 🎁 Enable download EAD functionality

app/components/blacklight/top_navbar_component.html.erb
Ref:
- https://github.com/notch8/archives_online/issues/115
The top navigation section had a header that said `Next Generation Archives Online` and a subheader that said `Indiana University`.
The top navigation section will only have a header that says `Indiana University`. The subheader has been removed.
<details>
</details>
<details>
</details>
=> i115 update header text

app/controllers/catalog_controller.rb
Removes the 'creator' index field from catalog controller to fix duplication issue: A user would see the same data twice when performing a catalog search.
Issue:
- #108
Original PR:
- https://github.com/notch8/archives_online/pull/131
=> [i108] follow up - removes display of duplicate creator content

.gitignore, Dockerfile, Gemfile, Gemfile.lock
This commit will add the missing styles for the printable view.  We needed the `bundle exec sass` command.
Ref:
- https://github.com/notch8/archives_online/issues/111
=> 🐛 Add missing styles to printable view

config/repositories.yml
Ref:
- https://github.com/notch8/archives_online/issues/89
The "Before you visit" property was displayed even though there was no content.
The "Before you visit" property should not display if there is no content.
<details>
</details>
<details>
</details>
=> 🐛 "Before you visit" should not display if empty

app/assets/stylesheets/arclight.scss, app/components/ngao/arclight/collection_context_component.html.erb, app/components/ngao/arclight/document_collection_hierarchy_component.html.erb, app/controllers/catalog_controller.rb, app/helpers/ngao/component_metadata_helper.rb
Improves the user experience in the collection hierarchy (side-by-side) view by addressing confusion caused by clickable components that lack detailed information beyond title and container.
Previously, components were clickable even if they only contained `<unittitle>` and `<container>` metadata. Since container information is usually visible in the sidebar, clicking these components led to a redundant detail view showing no new information.
This PR implements the following changes:
- Components in the collection hierarchy (`Ngao::Arclight::DocumentCollectionHierarchyComponent`) are now only rendered as links (clickable) if they possess metadata fields beyond `<unittitle>` and `<container>`.
- A new helper method (`Ngao::ComponentMetadataHelper.component_has_extra_metadata?`) was added …
=> 🎁 [i95] - Make hierarchy components clickable if extra metadata exists

app/assets/stylesheets/arclight.scss
Ref:
- https://github.com/notch8/archives_online/issues/147
The sidebar and main content scrolled as a single entity.
The sidebar scrolls independently of the main content.
<details>
https://github.com/user-attachments/assets/cdd02cc5-b661-47e5-a779-ff89f388406c
</details>
<details>
https://github.com/user-attachments/assets/32201493-e027-4b99-a52c-a1ac9e7f6a6d
</details>
=> i147 sidebar independent scroll

app/components/ngao/arclight/sidebar_component.html.erb
Ref:
- https://github.com/notch8/archives_online/issues/176
The tools section was in the sidebar under the collection details.
The tools section was removed.
<details>
</details>
<details>
</details>
=> i176 remove tools section

Dockerfile, Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, ops/nginx.sh, package.json, yarn.lock
This commit will remove the deprecated Sass gem in favor install Sass from yarn.
Ref:
- https://github.com/notch8/archives_online/issues/174
=> 🎁 Favor yarn sass over gem sass

app/assets/stylesheets/arclight.scss, app/components/ngao/arclight/collection_context_component.html.erb, app/components/ngao/arclight/document_component.html.erb, config/downloads.yml
1c7ba870787fd9ff99fb6ba3bf7617dea81ab109
This commit will configure Aeon by adding the archives.iu.edu address to
the ead download.  This does make our ead downloads look at the live
site which I think is fine for now since it would theoretically serve
the same content.
Ref:
- https://github.com/notch8/archives_online/issues/113
c9bef3702dd0ce756c78a557838124d82813c00f
This commit will move the Aeon request button to the collection context
area.
Ref:
- https://github.com/notch8/archives_online/issues/113
https://github.com/user-attachments/assets/a4ffaead-8d3c-4f18-9402-ea4f77e396d7
=> I113 aeon integration

app/components/ngao/blacklight/metadata_field_component_decorator.rb
Ref https://github.com/notch8/archives_online/issues/148
Overrides the label method to use the indexed <head> term as the label if one exists, with fallback to the prior behavior. 
<details>
<summary>Screenshot Before Change</summary>
</details>
<details>
<summary>Screenshot After Change</summary>
</details>
=> Add custom note labels

app/assets/stylesheets/arclight.scss, app/components/ngao/arclight/document_collection_hierarchy_component.html.erb
Ref:
- https://github.com/notch8/archives_online/issues/103
The physical container information was only available on the show page of each item.
The physical container information is in the sidebar next to each item's title.
<details>
</details>
<details>
</details>
=> i103 container info in collection context

app/assets/stylesheets/arclight.scss, app/components/ngao/arclight/document_collection_hierarchy_component.html.erb, app/components/ngao/arclight/document_collection_hierarchy_component.rb
Follow up 
Issue
- #95 
This PR reverts a [change](https://github.com/notch8/archives_online/pull/183) I made. I second guessed myself with what the client was asking for when they said to maintain the blue hyperlinks. The solution in staging ended up being too aggressive and my original implementation is preferred, as confirmed by the client: 
@brijmcla if i revert my latest changes this is what we have. Is this correct? 
<details> 
</details>
=> ♻️ [i95] - Reverts hyperlink styles

app/assets/stylesheets/arclight.scss
Ref:
- https://github.com/notch8/archives_online/issues/103
Missing styling from a merge conflict.
Physical collection content is visible in the sidebar.
<details>
<summary>Collection content sidebar</summary>
</details>
=> 🐛 i103 Physical container information on sidebar

app/components/blacklight/top_navbar_component.html.erb, app/components/ngao/arclight/header_component.rb, app/components/ngao/arclight/masthead_component.html.erb, app/components/ngao/arclight/masthead_component.rb, app/controllers/catalog_controller.rb
Ref:
- https://github.com/notch8/archives_online/issues/184
The Indiana University header was an internal nav to the root of the application. The masthead text did not have a link.
The Indiana University header now navigates to the Indiana homepage: `https://www.iu.edu/index.html` 
The masthead is now an internal nav to the root of the application
=> 🎁 i184 modifies header links
